### PR TITLE
build resolve fixed

### PR DESCRIPTION
**Pull request by YusufcanY**

### CODE REVIEW

**Comment by ejirocodes** [comment]
@YusufcanY, thanks a lot for getting this in. Have you tested it locally?

**Comment by YusufcanY** [comment]
> @YusufcanY, thanks a lot for getting this in. Have you tested it locally?

i was looking for how to do

**Comment by Niputi** [comment]
> > @YusufcanY, thanks a lot for getting this in. Have you tested it locally?
> 
> i was looking for how to do

you can edit the package json in your node module folder directly

**Comment by YusufcanY** [comment]
both solution didnt work.
Tried adding 
```
  "type" :  "module",
```

Tried changing the browser and module value:
changed to
```
  "browser": "dist/vue3-otp-input.esm.mjs",
  "module": "dist/vue3-otp-input.esm.mjs",
```
any other ideas?

**Comment by Niputi** [comment]
have just tried installing the package. there's something wrong with the publish. the build dist files are not present

**Comment by YusufcanY** [comment]
> have just tried installing the package. there's something wrong with the publish. the build dist files are not present

i think so

**Comment by Niputi** [comment]
This pull request would also need to edit the rollup config to emit the files with the `.mjs` extensions where it's a esm output file

**Comment by YusufcanY** [comment]
Can you solve it?

**Comment by Niputi** [comment]
> This pull request would also need to edit the rollup config to emit the files with the `.mjs` extensions where it's a esm output file

for this I could but won't before weekend as most of my day is at work 

> have just tried installing the package. there's something wrong with the publish. the build dist files are not present

This is on the author, as he publishes this module.

For now I would recommend copying source from this repo to your project until this module is fixed

**Comment by YusufcanY** [comment]
> > This pull request would also need to edit the rollup config to emit the files with the `.mjs` extensions where it's a esm output file
> 
> for this I could but won't before weekend as most of my day is spent at work
> 
> > have just tried installing the package. there's something wrong with the publish. the build dist files are not present
> 
> This is on the author, as he publishes this module.
> 
> For now I would recommend copying source from this repo to your project until this module is fixed

yes i will do that, because at work i need to use otp input and that is only solution for now

**Comment by ejirocodes** [comment]
@YusufcanY, @Niputi, I've fixed this and tried it on a fresh Vue 3, Vite project and it works fine. Please uninstall and install the latest version on [npm](https://www.npmjs.com/package/vue3-otp-input)

**Pull request closed without merging**
